In [32]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [33]:
!pip install nltk

In [34]:
import nltk
nltk.download('vader_lexicon')

[nltk_data] Downloading package vader_lexicon to /root/nltk_data...


True

In [35]:
#vader_lexicon
# bir metindeki duygusal tonları (pozitif, negatif, nötr) analiz etmek için kullanılır

In [36]:
from nltk.sentiment import SentimentIntensityAnalyzer

sia = SentimentIntensityAnalyzer()
print(sia.polarity_scores("This is a great cacti!"))

{'neg': 0.0, 'neu': 0.406, 'pos': 0.594, 'compound': 0.6588}


In [37]:
#neg : Negatif
#neu : Notr
#pos : Pozitif
#compound : Toplam puan

In [38]:

sia.polarity_scores(" I miss you so much ")

{'neg': 0.348, 'neu': 0.652, 'pos': 0.0, 'compound': -0.1531}

In [39]:
sia.polarity_scores("I am the data scientist of the future. because I love to learn ")

{'neg': 0.0, 'neu': 0.704, 'pos': 0.296, 'compound': 0.6369}

In [40]:
sia.polarity_scores("Can love forgive everything? ")

{'neg': 0.0, 'neu': 0.241, 'pos': 0.759, 'compound': 0.743}

In [41]:
sia.polarity_scores("I liked this music but it is not good as the other one")

{'neg': 0.207, 'neu': 0.666, 'pos': 0.127, 'compound': -0.298}

In [43]:
df = pd.read_csv('amazon.csv')
df.head(3)

reviewerID        asin reviewerName helpful  \
0  A3SBTW3WS4IQSN  B007WTAJTO          NaN  [0, 0]   
1  A18K1ODH1I2MVB  B007WTAJTO         0mie  [0, 0]   
2  A2FII3I2MBMUIA  B007WTAJTO          1K3  [0, 0]   

                                          reviewText  overall  \
0                                         No issues.      4.0   
1  Purchased this for my device, it worked as adv...      5.0   
2  it works as expected. I should have sprung for...      4.0   

                     summary  unixReviewTime  reviewTime  day_diff  \
0                 Four Stars      1406073600  2014-07-23       138   
1              MOAR SPACE!!!      1382659200  2013-10-25       409   
2  nothing to really say....      1356220800  2012-12-23       715   

   helpful_yes  total_vote  
0            0           0  
1            0           0  
2            0           0

In [44]:
df['reviewText'][0:10].apply(lambda x: sia.polarity_scores(x))

0    {'neg': 0.688, 'neu': 0.312, 'pos': 0.0, 'comp...
1    {'neg': 0.075, 'neu': 0.925, 'pos': 0.0, 'comp...
2    {'neg': 0.077, 'neu': 0.923, 'pos': 0.0, 'comp...
3    {'neg': 0.0, 'neu': 0.909, 'pos': 0.091, 'comp...
4    {'neg': 0.038, 'neu': 0.835, 'pos': 0.127, 'co...
5    {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...
6    {'neg': 0.063, 'neu': 0.745, 'pos': 0.192, 'co...
7    {'neg': 0.044, 'neu': 0.833, 'pos': 0.123, 'co...
8    {'neg': 0.091, 'neu': 0.909, 'pos': 0.0, 'comp...
9    {'neg': 0.0, 'neu': 0.627, 'pos': 0.373, 'comp...
Name: reviewText, dtype: object

In [45]:
df['reviewText'][0:10].apply(lambda x: sia.polarity_scores(x)['compound'])

0   -0.2960
1   -0.2960
2   -0.3089
3    0.7081
4    0.7087
5    0.0000
6    0.8992
7    0.7768
8   -0.2960
9    0.9167
Name: reviewText, dtype: float64

In [46]:
df['reviewText'] = df['reviewText'].fillna('')

In [47]:
df['polarity_score'] = df['reviewText'].apply(lambda x: sia.polarity_scores(x)['compound'])

In [48]:
print(df['reviewText'].dtype)

object


In [49]:
print(df['reviewText'].head())

0                                           No issues.
1    Purchased this for my device, it worked as adv...
2    it works as expected. I should have sprung for...
3    This think has worked out great.Had a diff. br...
4    Bought it with Retail Packaging, arrived legit...
Name: reviewText, dtype: object


In [50]:
df.head(3)

reviewerID        asin reviewerName helpful  \
0  A3SBTW3WS4IQSN  B007WTAJTO          NaN  [0, 0]   
1  A18K1ODH1I2MVB  B007WTAJTO         0mie  [0, 0]   
2  A2FII3I2MBMUIA  B007WTAJTO          1K3  [0, 0]   

                                          reviewText  overall  \
0                                         No issues.      4.0   
1  Purchased this for my device, it worked as adv...      5.0   
2  it works as expected. I should have sprung for...      4.0   

                     summary  unixReviewTime  reviewTime  day_diff  \
0                 Four Stars      1406073600  2014-07-23       138   
1              MOAR SPACE!!!      1382659200  2013-10-25       409   
2  nothing to really say....      1356220800  2012-12-23       715   

   helpful_yes  total_vote  polarity_score  
0            0           0         -0.2960  
1            0           0         -0.2960  
2            0           0         -0.3089

In [51]:

df['sentiment'] = df['reviewText'].apply(lambda x: "pos" if sia.polarity_scores(x)['compound'] > 0 else "neg")

In [52]:
df.head()

reviewerID        asin  reviewerName helpful  \
0  A3SBTW3WS4IQSN  B007WTAJTO           NaN  [0, 0]   
1  A18K1ODH1I2MVB  B007WTAJTO          0mie  [0, 0]   
2  A2FII3I2MBMUIA  B007WTAJTO           1K3  [0, 0]   
3   A3H99DFEG68SR  B007WTAJTO           1m2  [0, 0]   
4  A375ZM4U047O79  B007WTAJTO  2&amp;1/2Men  [0, 0]   

                                          reviewText  overall  \
0                                         No issues.      4.0   
1  Purchased this for my device, it worked as adv...      5.0   
2  it works as expected. I should have sprung for...      4.0   
3  This think has worked out great.Had a diff. br...      5.0   
4  Bought it with Retail Packaging, arrived legit...      5.0   

                                  summary  unixReviewTime  reviewTime  \
0                              Four Stars      1406073600  2014-07-23   
1                           MOAR SPACE!!!      1382659200  2013-10-25   
2               nothing to really say....      1356220800  2012-12-23   
3  Great buy at this price!!!  *** UPDATE      1384992000  2013-11-21   
4                        best deal around      1373673600  2013-07-13   

   day_diff  helpful_yes  total_vote  polarity_score sentiment  
0       138            0           0         -0.2960       neg  
1       409            0           0         -0.2960       neg  
2       715            0           0         -0.3089       neg  
3       382            0           0          0.7081       pos  
4       513            0           0          0.7087       pos

In [53]:
df['sentiment'].value_counts()

sentiment
pos    3746
neg    1169
Name: count, dtype: int64

In [54]:
df.groupby("sentiment")['overall'].mean()

sentiment
neg    4.089820
pos    4.742926
Name: overall, dtype: float64

In [55]:
from sklearn.preprocessing import LabelEncoder

In [56]:
df['sentiment'] = LabelEncoder().fit_transform(df['sentiment'])

In [57]:
df['sentiment']

0       0
1       0
2       0
3       1
4       1
       ..
4910    1
4911    1
4912    1
4913    1
4914    1
Name: sentiment, Length: 4915, dtype: int64

In [58]:
y =df['sentiment']
x =df['reviewText']

In [ ]:
#COUNT VECTORS
#TF-IDF VECTORS
#WORD EMBEDDING (Word2Vec , GloVe , Bert vs )

In [ ]:
#COUNT VECTORS
#kelimeler- words
#karakterlere- characters
#ngram


In [13]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [14]:
!python -m textblob.download_corpora

[nltk_data] Downloading package brown to /root/nltk_data...
[nltk_data]   Package brown is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package conll2000 to /root/nltk_data...
[nltk_data]   Package conll2000 is already up-to-date!
[nltk_data] Downloading package movie_reviews to /root/nltk_data...
[nltk_data]   Package movie_reviews is already up-to-date!
Finished.


In [16]:
import nltk
nltk.download('punkt_tab')
!python -m textblob.download_corpora

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


[nltk_data] Downloading package brown to /root/nltk_data...
[nltk_data]   Package brown is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package conll2000 to /root/nltk_data...
[nltk_data]   Package conll2000 is already up-to-date!
[nltk_data] Downloading package movie_reviews to /root/nltk_data...
[nltk_data]   Package movie_reviews is already up-to-date!
Finished.


In [17]:
from textblob import TextBlob
a = "I love natural language processing"
TextBlob(a).ngrams(3)

[WordList(['I', 'love', 'natural']),
 WordList(['love', 'natural', 'language']),
 WordList(['natural', 'language', 'processing'])]

In [19]:
from sklearn.feature_extraction.text import CountVectorizer. #corpus kelime vekt oluşturmak içn kulln. fonks
corpus = [
    'This is the first document.',
    'This document is the second document.',
    'And this is the third one.',
    'Is this the first document?',
]


In [24]:
vectorizer=CountVectorizer()
x = vectorizer.fit_transform(corpus) # Corpus’taki benzersiz kelimeleri belirler,Her kelimenin belge içinde kaç kez geçtiğini sayan bir matris oluşturur.
vectorizer.get_feature_names_out() #corpus’taki benzersiz kelimeleri (özellikleri) alfabetik sırayla döndürür. Kelimeler küçük harfe dönüştürülür ve noktalama işaretleri çıkarılır.

array(['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third',
       'this'], dtype=object)

In [25]:
x.toarray()

array([[0, 1, 1, 1, 0, 0, 1, 0, 1],
       [0, 2, 0, 1, 0, 1, 1, 0, 1],
       [1, 0, 0, 1, 1, 0, 1, 1, 1],
       [0, 1, 1, 1, 0, 0, 1, 0, 1]])

In [ ]:
# N-GRAMS FREKANS(kelime öbeklerine göre)

In [26]:
vectorizer2 =CountVectorizer(analyzer='word', ngram_range=(2, 2))
X2 = vectorizer2.fit_transform(corpus)
vectorizer2.get_feature_names_out()

array(['and this', 'document is', 'first document', 'is the', 'is this',
       'second document', 'the first', 'the second', 'the third',
       'third one', 'this document', 'this is', 'this the'], dtype=object)

In [28]:
X2.toarray()

array([[0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0],
       [1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0],
       [0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1]])

In [ ]:
#yukardaki rewiev text uygulayacğaım !

In [59]:
vectorizer = CountVectorizer()
x_count = vectorizer.fit_transform(df['reviewText'])

In [60]:
vectorizer.get_feature_names_out()
x_count.toarray()[10:15]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
#TF-IDF YÖNTEMİ


In [61]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf_idf_word_vectorizer = TfidfVectorizer()
tf_idf_word_vectorizer_vectors = tf_idf_word_vectorizer.fit_transform(df['reviewText'])

In [62]:
tf_idf_ngram_vectorizer = TfidfVectorizer(ngram_range=(2,3))
tf_idf_ngram_vectorizer_vectors = tf_idf_ngram_vectorizer.fit_transform(df['reviewText'])

In [ ]:
#Logistic Regression

In [70]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

In [71]:
log_model = LogisticRegression().fit(tf_idf_word_vectorizer_vectors, y)

In [73]:
cross_val_score(log_model,
                tf_idf_word_vectorizer_vectors,
                y,
                cv=5, scoring="accuracy").mean()

0.8118006103763988

In [ ]:
#(yorumları poz-neg)

In [74]:
new_rewiew = pd.Series("This product is great")


In [77]:
new_rewiew = pd.Series("look at that shit very bad")

In [78]:
new_rewiew = TfidfVectorizer().fit(x).transform(new_rewiew)

In [79]:
log_model.predict(new_rewiew)

array([0])

In [ ]:
#verisetimden örn yorum çekip bakalım !

In [81]:
pd.Series(df['reviewText'].sample(1).values)

0    Works great in my GoPro 3 Black. I will only b...
dtype: object

In [82]:
random_rewiev = pd.Series(df['reviewText'].sample(1).values)

In [83]:
new_rewiew = TfidfVectorizer().fit(x).transform(random_rewiev)

In [84]:
log_model.predict(new_rewiew)

array([1])

In [ ]:
#2 ornk

In [86]:
 pd.Series(df['reviewText'].sample(1).values)

0    its soooooo fast and gives you alot of space, ...
dtype: object

In [87]:
random_rewiev = pd.Series(df['reviewText'].sample(1).values)

In [88]:
new_rewiew = TfidfVectorizer().fit(x).transform(random_rewiev)

In [89]:
log_model.predict(new_rewiew)

array([0])

In [ ]:
#Hıper parametre

In [104]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV # Add this line to import GridSearchCV
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(random_state=17)

In [105]:
rf_params = {"max_depth" : [8, None],  #model derinlik
             "max_features" : [7, "auto"], #herdüğümdeki özellik
             "min_samples_split" : [2, 5, 8],#bir yapraktaki ne kadar sample olması gerektiği
             "n_estimators" : [100, 200]} # ağaç sayısı

In [106]:
rf_best_grid = GridSearchCV(rf_model,
                            rf_params,
                            cv=5,  # 5 katmana bölünür
                            n_jobs=-1,  # Paralel çalışmayı etkinleştir
                            verbose=1).fit(x_count, y)#işlemin ilerleyişini ekrana yazdırır

Fitting 5 folds for each of 24 candidates, totalling 120 fits


/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:528: FitFailedWarning: 
60 fits failed out of a total of 120.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
60 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/base.py", line 1382, in wrapper
    estimator._validate_params()
  File "/usr/local/lib/python3.10/dist-packages/sklearn/base.py", line 436, in _validate_params
    validate_parameter_constraints(
  File "/usr/local/lib/python3.10/dist-packages/sklearn/utils/

In [107]:
rf_best_grid.best_params_

{'max_depth': None,
 'max_features': 7,
 'min_samples_split': 2,
 'n_estimators': 100}

In [109]:
rf_final = rf_model.set_params(**rf_best_grid.best_params_, random_state=17).fit(x_count, y)

In [110]:
cross_val_score(rf_final, x_count, y, cv=5, n_jobs=-1).mean()

0.767446592065107